/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesFactory
 * @model kind="package"
 * @generated
 */
public interface DSLPoliciesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dSLPolicies";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.gw4e/dsl/DSLPolicies";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dSLPolicies";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLPoliciesPackage eINSTANCE = gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl.init();

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.ModelImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Graph Policies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GRAPH_POLICIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.GraphPoliciesImpl <em>Graph Policies</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.GraphPoliciesImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getGraphPolicies()
   * @generated
   */
  int GRAPH_POLICIES = 1;

  /**
   * The feature id for the '<em><b>Graph Model Policies</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_POLICIES__GRAPH_MODEL_POLICIES = 0;

  /**
   * The feature id for the '<em><b>Policies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_POLICIES__POLICIES = 1;

  /**
   * The number of structural features of the '<em>Graph Policies</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_POLICIES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.SeverityImpl <em>Severity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.SeverityImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getSeverity()
   * @generated
   */
  int SEVERITY = 2;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEVERITY__LEVEL = 0;

  /**
   * The number of structural features of the '<em>Severity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEVERITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.PoliciesImpl <em>Policies</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.PoliciesImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getPolicies()
   * @generated
   */
  int POLICIES = 3;

  /**
   * The feature id for the '<em><b>Nocheck</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICIES__NOCHECK = 0;

  /**
   * The feature id for the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICIES__SYNC = 1;

  /**
   * The feature id for the '<em><b>Pathgenerator</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICIES__PATHGENERATOR = 2;

  /**
   * The feature id for the '<em><b>Severity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICIES__SEVERITY = 3;

  /**
   * The number of structural features of the '<em>Policies</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POLICIES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.PathGeneratorStopConditionImpl <em>Path Generator Stop Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.PathGeneratorStopConditionImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getPathGeneratorStopCondition()
   * @generated
   */
  int PATH_GENERATOR_STOP_CONDITION = 4;

  /**
   * The feature id for the '<em><b>Algorithm Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_GENERATOR_STOP_CONDITION__ALGORITHM_TYPE = 0;

  /**
   * The feature id for the '<em><b>Stop Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_GENERATOR_STOP_CONDITION__STOP_CONDITION = 1;

  /**
   * The feature id for the '<em><b>Stop Conditionype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_GENERATOR_STOP_CONDITION__STOP_CONDITIONYPE = 2;

  /**
   * The number of structural features of the '<em>Path Generator Stop Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_GENERATOR_STOP_CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.AlgorithmTypeImpl <em>Algorithm Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.AlgorithmTypeImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getAlgorithmType()
   * @generated
   */
  int ALGORITHM_TYPE = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Algorithm Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.StopConditionImpl <em>Stop Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.StopConditionImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getStopCondition()
   * @generated
   */
  int STOP_CONDITION = 6;

  /**
   * The feature id for the '<em><b>Pathtype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_CONDITION__PATHTYPE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_CONDITION__VALUE = 1;

  /**
   * The feature id for the '<em><b>Percentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_CONDITION__PERCENTAGE = 2;

  /**
   * The feature id for the '<em><b>Graphelement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_CONDITION__GRAPHELEMENT = 3;

  /**
   * The number of structural features of the '<em>Stop Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOP_CONDITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.GraphElementImpl <em>Graph Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.GraphElementImpl
   * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getGraphElement()
   * @generated
   */
  int GRAPH_ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Graph Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_ELEMENT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link gw4e.eclipse.dsl.dSLPolicies.Model#getGraphPolicies <em>Graph Policies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Graph Policies</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Model#getGraphPolicies()
   * @see #getModel()
   * @generated
   */
  EReference getModel_GraphPolicies();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies <em>Graph Policies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graph Policies</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.GraphPolicies
   * @generated
   */
  EClass getGraphPolicies();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getGraphModelPolicies <em>Graph Model Policies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Graph Model Policies</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getGraphModelPolicies()
   * @see #getGraphPolicies()
   * @generated
   */
  EAttribute getGraphPolicies_GraphModelPolicies();

  /**
   * Returns the meta object for the containment reference list '{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getPolicies <em>Policies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Policies</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getPolicies()
   * @see #getGraphPolicies()
   * @generated
   */
  EReference getGraphPolicies_Policies();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.Severity <em>Severity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Severity</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Severity
   * @generated
   */
  EClass getSeverity();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.Severity#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Severity#getLevel()
   * @see #getSeverity()
   * @generated
   */
  EAttribute getSeverity_Level();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.Policies <em>Policies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Policies</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Policies
   * @generated
   */
  EClass getPolicies();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isNocheck <em>Nocheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nocheck</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Policies#isNocheck()
   * @see #getPolicies()
   * @generated
   */
  EAttribute getPolicies_Nocheck();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isSync <em>Sync</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sync</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Policies#isSync()
   * @see #getPolicies()
   * @generated
   */
  EAttribute getPolicies_Sync();

  /**
   * Returns the meta object for the containment reference list '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#getPathgenerator <em>Pathgenerator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pathgenerator</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Policies#getPathgenerator()
   * @see #getPolicies()
   * @generated
   */
  EReference getPolicies_Pathgenerator();

  /**
   * Returns the meta object for the containment reference '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#getSeverity <em>Severity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Severity</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.Policies#getSeverity()
   * @see #getPolicies()
   * @generated
   */
  EReference getPolicies_Severity();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition <em>Path Generator Stop Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Generator Stop Condition</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition
   * @generated
   */
  EClass getPathGeneratorStopCondition();

  /**
   * Returns the meta object for the containment reference '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getAlgorithmType <em>Algorithm Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algorithm Type</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getAlgorithmType()
   * @see #getPathGeneratorStopCondition()
   * @generated
   */
  EReference getPathGeneratorStopCondition_AlgorithmType();

  /**
   * Returns the meta object for the containment reference '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopCondition <em>Stop Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stop Condition</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopCondition()
   * @see #getPathGeneratorStopCondition()
   * @generated
   */
  EReference getPathGeneratorStopCondition_StopCondition();

  /**
   * Returns the meta object for the containment reference '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopConditionype <em>Stop Conditionype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stop Conditionype</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopConditionype()
   * @see #getPathGeneratorStopCondition()
   * @generated
   */
  EReference getPathGeneratorStopCondition_StopConditionype();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.AlgorithmType <em>Algorithm Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm Type</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.AlgorithmType
   * @generated
   */
  EClass getAlgorithmType();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.AlgorithmType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.AlgorithmType#getType()
   * @see #getAlgorithmType()
   * @generated
   */
  EAttribute getAlgorithmType_Type();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition <em>Stop Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop Condition</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.StopCondition
   * @generated
   */
  EClass getStopCondition();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPathtype <em>Pathtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pathtype</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPathtype()
   * @see #getStopCondition()
   * @generated
   */
  EAttribute getStopCondition_Pathtype();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.StopCondition#getValue()
   * @see #getStopCondition()
   * @generated
   */
  EAttribute getStopCondition_Value();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPercentage <em>Percentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Percentage</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPercentage()
   * @see #getStopCondition()
   * @generated
   */
  EAttribute getStopCondition_Percentage();

  /**
   * Returns the meta object for the containment reference '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getGraphelement <em>Graphelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Graphelement</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.StopCondition#getGraphelement()
   * @see #getStopCondition()
   * @generated
   */
  EReference getStopCondition_Graphelement();

  /**
   * Returns the meta object for class '{@link gw4e.eclipse.dsl.dSLPolicies.GraphElement <em>Graph Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graph Element</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.GraphElement
   * @generated
   */
  EClass getGraphElement();

  /**
   * Returns the meta object for the attribute '{@link gw4e.eclipse.dsl.dSLPolicies.GraphElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gw4e.eclipse.dsl.dSLPolicies.GraphElement#getName()
   * @see #getGraphElement()
   * @generated
   */
  EAttribute getGraphElement_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DSLPoliciesFactory getDSLPoliciesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.ModelImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Graph Policies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GRAPH_POLICIES = eINSTANCE.getModel_GraphPolicies();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.GraphPoliciesImpl <em>Graph Policies</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.GraphPoliciesImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getGraphPolicies()
     * @generated
     */
    EClass GRAPH_POLICIES = eINSTANCE.getGraphPolicies();

    /**
     * The meta object literal for the '<em><b>Graph Model Policies</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPH_POLICIES__GRAPH_MODEL_POLICIES = eINSTANCE.getGraphPolicies_GraphModelPolicies();

    /**
     * The meta object literal for the '<em><b>Policies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPH_POLICIES__POLICIES = eINSTANCE.getGraphPolicies_Policies();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.SeverityImpl <em>Severity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.SeverityImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getSeverity()
     * @generated
     */
    EClass SEVERITY = eINSTANCE.getSeverity();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEVERITY__LEVEL = eINSTANCE.getSeverity_Level();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.PoliciesImpl <em>Policies</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.PoliciesImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getPolicies()
     * @generated
     */
    EClass POLICIES = eINSTANCE.getPolicies();

    /**
     * The meta object literal for the '<em><b>Nocheck</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICIES__NOCHECK = eINSTANCE.getPolicies_Nocheck();

    /**
     * The meta object literal for the '<em><b>Sync</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POLICIES__SYNC = eINSTANCE.getPolicies_Sync();

    /**
     * The meta object literal for the '<em><b>Pathgenerator</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLICIES__PATHGENERATOR = eINSTANCE.getPolicies_Pathgenerator();

    /**
     * The meta object literal for the '<em><b>Severity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POLICIES__SEVERITY = eINSTANCE.getPolicies_Severity();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.PathGeneratorStopConditionImpl <em>Path Generator Stop Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.PathGeneratorStopConditionImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getPathGeneratorStopCondition()
     * @generated
     */
    EClass PATH_GENERATOR_STOP_CONDITION = eINSTANCE.getPathGeneratorStopCondition();

    /**
     * The meta object literal for the '<em><b>Algorithm Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_GENERATOR_STOP_CONDITION__ALGORITHM_TYPE = eINSTANCE.getPathGeneratorStopCondition_AlgorithmType();

    /**
     * The meta object literal for the '<em><b>Stop Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_GENERATOR_STOP_CONDITION__STOP_CONDITION = eINSTANCE.getPathGeneratorStopCondition_StopCondition();

    /**
     * The meta object literal for the '<em><b>Stop Conditionype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_GENERATOR_STOP_CONDITION__STOP_CONDITIONYPE = eINSTANCE.getPathGeneratorStopCondition_StopConditionype();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.AlgorithmTypeImpl <em>Algorithm Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.AlgorithmTypeImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getAlgorithmType()
     * @generated
     */
    EClass ALGORITHM_TYPE = eINSTANCE.getAlgorithmType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM_TYPE__TYPE = eINSTANCE.getAlgorithmType_Type();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.StopConditionImpl <em>Stop Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.StopConditionImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getStopCondition()
     * @generated
     */
    EClass STOP_CONDITION = eINSTANCE.getStopCondition();

    /**
     * The meta object literal for the '<em><b>Pathtype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP_CONDITION__PATHTYPE = eINSTANCE.getStopCondition_Pathtype();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP_CONDITION__VALUE = eINSTANCE.getStopCondition_Value();

    /**
     * The meta object literal for the '<em><b>Percentage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOP_CONDITION__PERCENTAGE = eINSTANCE.getStopCondition_Percentage();

    /**
     * The meta object literal for the '<em><b>Graphelement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOP_CONDITION__GRAPHELEMENT = eINSTANCE.getStopCondition_Graphelement();

    /**
     * The meta object literal for the '{@link gw4e.eclipse.dsl.dSLPolicies.impl.GraphElementImpl <em>Graph Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.GraphElementImpl
     * @see gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesPackageImpl#getGraphElement()
     * @generated
     */
    EClass GRAPH_ELEMENT = eINSTANCE.getGraphElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPH_ELEMENT__NAME = eINSTANCE.getGraphElement_Name();

  }

} //DSLPoliciesPackage
