/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage
 * @generated
 */
public interface DSLPoliciesFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLPoliciesFactory eINSTANCE = gw4e.eclipse.dsl.dSLPolicies.impl.DSLPoliciesFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Graph Policies</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graph Policies</em>'.
   * @generated
   */
  GraphPolicies createGraphPolicies();

  /**
   * Returns a new object of class '<em>Severity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Severity</em>'.
   * @generated
   */
  Severity createSeverity();

  /**
   * Returns a new object of class '<em>Policies</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Policies</em>'.
   * @generated
   */
  Policies createPolicies();

  /**
   * Returns a new object of class '<em>Path Generator Stop Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Generator Stop Condition</em>'.
   * @generated
   */
  PathGeneratorStopCondition createPathGeneratorStopCondition();

  /**
   * Returns a new object of class '<em>Algorithm Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Algorithm Type</em>'.
   * @generated
   */
  AlgorithmType createAlgorithmType();

  /**
   * Returns a new object of class '<em>Stop Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stop Condition</em>'.
   * @generated
   */
  StopCondition createStopCondition();

  /**
   * Returns a new object of class '<em>Graph Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graph Element</em>'.
   * @generated
   */
  GraphElement createGraphElement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DSLPoliciesPackage getDSLPoliciesPackage();

} //DSLPoliciesFactory
