/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graph Policies</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getGraphModelPolicies <em>Graph Model Policies</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getPolicies <em>Policies</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getGraphPolicies()
 * @model
 * @generated
 */
public interface GraphPolicies extends EObject
{
  /**
   * Returns the value of the '<em><b>Graph Model Policies</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Graph Model Policies</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graph Model Policies</em>' attribute.
   * @see #setGraphModelPolicies(String)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getGraphPolicies_GraphModelPolicies()
   * @model
   * @generated
   */
  String getGraphModelPolicies();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies#getGraphModelPolicies <em>Graph Model Policies</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Graph Model Policies</em>' attribute.
   * @see #getGraphModelPolicies()
   * @generated
   */
  void setGraphModelPolicies(String value);

  /**
   * Returns the value of the '<em><b>Policies</b></em>' containment reference list.
   * The list contents are of type {@link gw4e.eclipse.dsl.dSLPolicies.Policies}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Policies</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Policies</em>' containment reference list.
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getGraphPolicies_Policies()
   * @model containment="true"
   * @generated
   */
  EList<Policies> getPolicies();

} // GraphPolicies
