/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Model#getGraphPolicies <em>Graph Policies</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Graph Policies</b></em>' containment reference list.
   * The list contents are of type {@link gw4e.eclipse.dsl.dSLPolicies.GraphPolicies}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Graph Policies</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graph Policies</em>' containment reference list.
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getModel_GraphPolicies()
   * @model containment="true"
   * @generated
   */
  EList<GraphPolicies> getGraphPolicies();

} // Model
