/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Generator Stop Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getAlgorithmType <em>Algorithm Type</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopCondition <em>Stop Condition</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopConditionype <em>Stop Conditionype</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPathGeneratorStopCondition()
 * @model
 * @generated
 */
public interface PathGeneratorStopCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Algorithm Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Algorithm Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm Type</em>' containment reference.
   * @see #setAlgorithmType(AlgorithmType)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPathGeneratorStopCondition_AlgorithmType()
   * @model containment="true"
   * @generated
   */
  AlgorithmType getAlgorithmType();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getAlgorithmType <em>Algorithm Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm Type</em>' containment reference.
   * @see #getAlgorithmType()
   * @generated
   */
  void setAlgorithmType(AlgorithmType value);

  /**
   * Returns the value of the '<em><b>Stop Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stop Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop Condition</em>' containment reference.
   * @see #setStopCondition(StopCondition)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPathGeneratorStopCondition_StopCondition()
   * @model containment="true"
   * @generated
   */
  StopCondition getStopCondition();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopCondition <em>Stop Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop Condition</em>' containment reference.
   * @see #getStopCondition()
   * @generated
   */
  void setStopCondition(StopCondition value);

  /**
   * Returns the value of the '<em><b>Stop Conditionype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stop Conditionype</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop Conditionype</em>' containment reference.
   * @see #setStopConditionype(StopCondition)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPathGeneratorStopCondition_StopConditionype()
   * @model containment="true"
   * @generated
   */
  StopCondition getStopConditionype();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition#getStopConditionype <em>Stop Conditionype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop Conditionype</em>' containment reference.
   * @see #getStopConditionype()
   * @generated
   */
  void setStopConditionype(StopCondition value);

} // PathGeneratorStopCondition
