/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Policies</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isNocheck <em>Nocheck</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isSync <em>Sync</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Policies#getPathgenerator <em>Pathgenerator</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Policies#getSeverity <em>Severity</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPolicies()
 * @model
 * @generated
 */
public interface Policies extends EObject
{
  /**
   * Returns the value of the '<em><b>Nocheck</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nocheck</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nocheck</em>' attribute.
   * @see #setNocheck(boolean)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPolicies_Nocheck()
   * @model
   * @generated
   */
  boolean isNocheck();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isNocheck <em>Nocheck</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nocheck</em>' attribute.
   * @see #isNocheck()
   * @generated
   */
  void setNocheck(boolean value);

  /**
   * Returns the value of the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sync</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sync</em>' attribute.
   * @see #setSync(boolean)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPolicies_Sync()
   * @model
   * @generated
   */
  boolean isSync();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#isSync <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sync</em>' attribute.
   * @see #isSync()
   * @generated
   */
  void setSync(boolean value);

  /**
   * Returns the value of the '<em><b>Pathgenerator</b></em>' containment reference list.
   * The list contents are of type {@link gw4e.eclipse.dsl.dSLPolicies.PathGeneratorStopCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pathgenerator</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pathgenerator</em>' containment reference list.
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPolicies_Pathgenerator()
   * @model containment="true"
   * @generated
   */
  EList<PathGeneratorStopCondition> getPathgenerator();

  /**
   * Returns the value of the '<em><b>Severity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Severity</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Severity</em>' containment reference.
   * @see #setSeverity(Severity)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getPolicies_Severity()
   * @model containment="true"
   * @generated
   */
  Severity getSeverity();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.Policies#getSeverity <em>Severity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Severity</em>' containment reference.
   * @see #getSeverity()
   * @generated
   */
  void setSeverity(Severity value);

} // Policies
