/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Severity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.Severity#getLevel <em>Level</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getSeverity()
 * @model
 * @generated
 */
public interface Severity extends EObject
{
  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Level</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see #setLevel(String)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getSeverity_Level()
   * @model
   * @generated
   */
  String getLevel();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.Severity#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see #getLevel()
   * @generated
   */
  void setLevel(String value);

} // Severity
