/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stop Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPathtype <em>Pathtype</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getValue <em>Value</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPercentage <em>Percentage</em>}</li>
 *   <li>{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getGraphelement <em>Graphelement</em>}</li>
 * </ul>
 *
 * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getStopCondition()
 * @model
 * @generated
 */
public interface StopCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Pathtype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pathtype</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pathtype</em>' attribute.
   * @see #setPathtype(String)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getStopCondition_Pathtype()
   * @model
   * @generated
   */
  String getPathtype();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPathtype <em>Pathtype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pathtype</em>' attribute.
   * @see #getPathtype()
   * @generated
   */
  void setPathtype(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getStopCondition_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Percentage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Percentage</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Percentage</em>' attribute.
   * @see #setPercentage(String)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getStopCondition_Percentage()
   * @model
   * @generated
   */
  String getPercentage();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getPercentage <em>Percentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Percentage</em>' attribute.
   * @see #getPercentage()
   * @generated
   */
  void setPercentage(String value);

  /**
   * Returns the value of the '<em><b>Graphelement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Graphelement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Graphelement</em>' containment reference.
   * @see #setGraphelement(GraphElement)
   * @see gw4e.eclipse.dsl.dSLPolicies.DSLPoliciesPackage#getStopCondition_Graphelement()
   * @model containment="true"
   * @generated
   */
  GraphElement getGraphelement();

  /**
   * Sets the value of the '{@link gw4e.eclipse.dsl.dSLPolicies.StopCondition#getGraphelement <em>Graphelement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Graphelement</em>' containment reference.
   * @see #getGraphelement()
   * @generated
   */
  void setGraphelement(GraphElement value);

} // StopCondition
