/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DSLPoliciesRuntimeModule extends AbstractDSLPoliciesRuntimeModule {
}
