/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLPoliciesStandaloneSetup extends DSLPoliciesStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLPoliciesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
