/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ui;

import gw4e.eclipse.dsl.ui.AbstractDSLPoliciesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DSLPoliciesUiModule extends AbstractDSLPoliciesUiModule {
  public DSLPoliciesUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
