/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractDSLPoliciesScopeProvider extends XbaseBatchScopeProvider {
}
