/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ui;

import com.google.inject.Injector;
import gw4e.eclipse.dsl.policies.ui.internal.PoliciesActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSLPoliciesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PoliciesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PoliciesActivator.getInstance().getInjector(PoliciesActivator.GW4E_ECLIPSE_DSL_DSLPOLICIES);
	}
	
}
