/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ui.tests;

import com.google.inject.Injector;
import gw4e.eclipse.dsl.policies.ui.internal.PoliciesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DSLPoliciesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PoliciesActivator.getInstance().getInjector("gw4e.eclipse.dsl.DSLPolicies");
	}

}
