/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DSLPoliciesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("gw4e/eclipse/dsl/parser/antlr/internal/InternalDSLPolicies.tokens");
	}
}
