/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.parser.antlr;

import com.google.inject.Inject;
import gw4e.eclipse.dsl.parser.antlr.internal.InternalDSLPoliciesParser;
import gw4e.eclipse.dsl.services.DSLPoliciesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DSLPoliciesParser extends AbstractAntlrParser {

	@Inject
	private DSLPoliciesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDSLPoliciesParser createParser(XtextTokenStream stream) {
		return new InternalDSLPoliciesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DSLPoliciesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLPoliciesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
