/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DSLPoliciesScopeProvider extends AbstractDSLPoliciesScopeProvider {

}
