/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.IXtextEditorCallback

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DSLPoliciesUiModule extends AbstractDSLPoliciesUiModule {
	override Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return null;
	}
}
