/*
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DSLPoliciesUiModule extends AbstractDSLPoliciesUiModule {
}
