/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gw4e.eclipse.dsl.DSLPoliciesRuntimeModule;
import gw4e.eclipse.dsl.DSLPoliciesStandaloneSetup;
import gw4e.eclipse.dsl.ide.DSLPoliciesIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DSLPoliciesIdeSetup extends DSLPoliciesStandaloneSetup {
  @Override
  public Injector createInjector() {
    DSLPoliciesRuntimeModule _dSLPoliciesRuntimeModule = new DSLPoliciesRuntimeModule();
    DSLPoliciesIdeModule _dSLPoliciesIdeModule = new DSLPoliciesIdeModule();
    return Guice.createInjector(Modules2.mixin(_dSLPoliciesRuntimeModule, _dSLPoliciesIdeModule));
  }
}
