/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.ide;

import gw4e.eclipse.dsl.ide.AbstractDSLPoliciesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DSLPoliciesIdeModule extends AbstractDSLPoliciesIdeModule {
}
