/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.scoping;

import gw4e.eclipse.dsl.scoping.AbstractDSLPoliciesScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DSLPoliciesScopeProvider extends AbstractDSLPoliciesScopeProvider {
}
