/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl.dSLPolicies.impl;

import gw4e.eclipse.dsl.dSLPolicies.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSLPoliciesFactoryImpl extends EFactoryImpl implements DSLPoliciesFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DSLPoliciesFactory init()
  {
    try
    {
      DSLPoliciesFactory theDSLPoliciesFactory = (DSLPoliciesFactory)EPackage.Registry.INSTANCE.getEFactory(DSLPoliciesPackage.eNS_URI);
      if (theDSLPoliciesFactory != null)
      {
        return theDSLPoliciesFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DSLPoliciesFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DSLPoliciesFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DSLPoliciesPackage.MODEL: return createModel();
      case DSLPoliciesPackage.GRAPH_POLICIES: return createGraphPolicies();
      case DSLPoliciesPackage.SEVERITY: return createSeverity();
      case DSLPoliciesPackage.POLICIES: return createPolicies();
      case DSLPoliciesPackage.PATH_GENERATOR_STOP_CONDITION: return createPathGeneratorStopCondition();
      case DSLPoliciesPackage.ALGORITHM_TYPE: return createAlgorithmType();
      case DSLPoliciesPackage.STOP_CONDITION: return createStopCondition();
      case DSLPoliciesPackage.GRAPH_ELEMENT: return createGraphElement();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphPolicies createGraphPolicies()
  {
    GraphPoliciesImpl graphPolicies = new GraphPoliciesImpl();
    return graphPolicies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Severity createSeverity()
  {
    SeverityImpl severity = new SeverityImpl();
    return severity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Policies createPolicies()
  {
    PoliciesImpl policies = new PoliciesImpl();
    return policies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PathGeneratorStopCondition createPathGeneratorStopCondition()
  {
    PathGeneratorStopConditionImpl pathGeneratorStopCondition = new PathGeneratorStopConditionImpl();
    return pathGeneratorStopCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AlgorithmType createAlgorithmType()
  {
    AlgorithmTypeImpl algorithmType = new AlgorithmTypeImpl();
    return algorithmType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StopCondition createStopCondition()
  {
    StopConditionImpl stopCondition = new StopConditionImpl();
    return stopCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphElement createGraphElement()
  {
    GraphElementImpl graphElement = new GraphElementImpl();
    return graphElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DSLPoliciesPackage getDSLPoliciesPackage()
  {
    return (DSLPoliciesPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DSLPoliciesPackage getPackage()
  {
    return DSLPoliciesPackage.eINSTANCE;
  }

} //DSLPoliciesFactoryImpl
