/**
 * generated by Xtext 2.12.0
 */
package gw4e.eclipse.dsl;

import gw4e.eclipse.dsl.DSLPoliciesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLPoliciesStandaloneSetup extends DSLPoliciesStandaloneSetupGenerated {
  public static void doSetup() {
    new DSLPoliciesStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
